/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PeringkatRouteImport } from './routes/peringkat'
import { Route as PetugasRouteImport } from './routes/petugas'
import { Route as SiswaRouteImport } from './routes/siswa'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminChallengeRouteImport } from './routes/admin.challenge'
import { Route as AdminLaporanRouteImport } from './routes/admin.laporan'
import { Route as AdminPenggunaRouteImport } from './routes/admin.pengguna'
import { Route as PetugasIndexRouteImport } from './routes/petugas.index'
import { Route as SiswaIndexRouteImport } from './routes/siswa.index'
import { Route as SiswaProfilRouteImport } from './routes/siswa.profil'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PeringkatRoute = PeringkatRouteImport.update({
  id: '/peringkat',
  path: '/peringkat',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasRoute = PetugasRouteImport.update({
  id: '/petugas',
  path: '/petugas',
  getParentRoute: () => rootRouteImport,
} as any)
const SiswaRoute = SiswaRouteImport.update({
  id: '/siswa',
  path: '/siswa',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChallengeRoute = AdminChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLaporanRoute = AdminLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenggunaRoute = AdminPenggunaRouteImport.update({
  id: '/pengguna',
  path: '/pengguna',
  getParentRoute: () => AdminRoute,
} as any)
const PetugasIndexRoute = PetugasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PetugasRoute,
} as any)
const SiswaIndexRoute = SiswaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiswaRoute,
} as any)
const SiswaProfilRoute = SiswaProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => SiswaRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/peringkat': typeof PeringkatRoute
  '/petugas': typeof PetugasRouteWithChildren
  '/siswa': typeof SiswaRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/siswa/profil': typeof SiswaProfilRoute
  '/admin/': typeof AdminIndexRoute
  '/petugas/': typeof PetugasIndexRoute
  '/siswa/': typeof SiswaIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/peringkat': typeof PeringkatRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/siswa/profil': typeof SiswaProfilRoute
  '/admin': typeof AdminIndexRoute
  '/petugas': typeof PetugasIndexRoute
  '/siswa': typeof SiswaIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/peringkat': typeof PeringkatRoute
  '/petugas': typeof PetugasRouteWithChildren
  '/siswa': typeof SiswaRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/laporan': typeof AdminLaporanRoute
  '/admin/pengguna': typeof AdminPenggunaRoute
  '/siswa/profil': typeof SiswaProfilRoute
  '/admin/': typeof AdminIndexRoute
  '/petugas/': typeof PetugasIndexRoute
  '/siswa/': typeof SiswaIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/peringkat'
    | '/petugas'
    | '/siswa'
    | '/teacher'
    | '/admin/challenge'
    | '/admin/laporan'
    | '/admin/pengguna'
    | '/siswa/profil'
    | '/admin/'
    | '/petugas/'
    | '/siswa/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/peringkat'
    | '/admin/challenge'
    | '/admin/laporan'
    | '/admin/pengguna'
    | '/siswa/profil'
    | '/admin'
    | '/petugas'
    | '/siswa'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/peringkat'
    | '/petugas'
    | '/siswa'
    | '/teacher'
    | '/admin/challenge'
    | '/admin/laporan'
    | '/admin/pengguna'
    | '/siswa/profil'
    | '/admin/'
    | '/petugas/'
    | '/siswa/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  PeringkatRoute: typeof PeringkatRoute
  PetugasRoute: typeof PetugasRouteWithChildren
  SiswaRoute: typeof SiswaRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peringkat': {
      id: '/peringkat'
      path: '/peringkat'
      fullPath: '/peringkat'
      preLoaderRoute: typeof PeringkatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas': {
      id: '/petugas'
      path: '/petugas'
      fullPath: '/petugas'
      preLoaderRoute: typeof PetugasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/siswa': {
      id: '/siswa'
      path: '/siswa'
      fullPath: '/siswa'
      preLoaderRoute: typeof SiswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/challenge': {
      id: '/admin/challenge'
      path: '/challenge'
      fullPath: '/admin/challenge'
      preLoaderRoute: typeof AdminChallengeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/laporan': {
      id: '/admin/laporan'
      path: '/laporan'
      fullPath: '/admin/laporan'
      preLoaderRoute: typeof AdminLaporanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengguna': {
      id: '/admin/pengguna'
      path: '/pengguna'
      fullPath: '/admin/pengguna'
      preLoaderRoute: typeof AdminPenggunaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/petugas/': {
      id: '/petugas/'
      path: '/'
      fullPath: '/petugas/'
      preLoaderRoute: typeof PetugasIndexRouteImport
      parentRoute: typeof PetugasRoute
    }
    '/siswa/': {
      id: '/siswa/'
      path: '/'
      fullPath: '/siswa/'
      preLoaderRoute: typeof SiswaIndexRouteImport
      parentRoute: typeof SiswaRoute
    }
    '/siswa/profil': {
      id: '/siswa/profil'
      path: '/profil'
      fullPath: '/siswa/profil'
      preLoaderRoute: typeof SiswaProfilRouteImport
      parentRoute: typeof SiswaRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
  }
}

interface AdminRouteChildren {
  AdminChallengeRoute: typeof AdminChallengeRoute
  AdminLaporanRoute: typeof AdminLaporanRoute
  AdminPenggunaRoute: typeof AdminPenggunaRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminChallengeRoute: AdminChallengeRoute,
  AdminLaporanRoute: AdminLaporanRoute,
  AdminPenggunaRoute: AdminPenggunaRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PetugasRouteChildren {
  PetugasIndexRoute: typeof PetugasIndexRoute
}

const PetugasRouteChildren: PetugasRouteChildren = {
  PetugasIndexRoute: PetugasIndexRoute,
}

const PetugasRouteWithChildren =
  PetugasRoute._addFileChildren(PetugasRouteChildren)

interface SiswaRouteChildren {
  SiswaProfilRoute: typeof SiswaProfilRoute
  SiswaIndexRoute: typeof SiswaIndexRoute
}

const SiswaRouteChildren: SiswaRouteChildren = {
  SiswaProfilRoute: SiswaProfilRoute,
  SiswaIndexRoute: SiswaIndexRoute,
}

const SiswaRouteWithChildren = SiswaRoute._addFileChildren(SiswaRouteChildren)

interface TeacherRouteChildren {
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  PeringkatRoute: PeringkatRoute,
  PetugasRoute: PetugasRouteWithChildren,
  SiswaRoute: SiswaRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
